name:
  "analysis name"
api_keys:
  abuseipdb: "11111"
  virustotal: "22222"
  securitytrails: "33333"
  shodan: "44444"
feeds:
  tor_node_list: "https://www.dan.me.uk/torlist/"
  tor_exit_node_list: "https://www.dan.me.uk/torlist/?exit"
  crypto_domains: "https://blocklistproject.github.io/Lists/alt-version/crypto-nl.txt"
  ja3_rules: "https://rules.emergingthreats.net/open/suricata-5.0/rules/emerging-ja3.rules"
enrichment_services:
  abuseipdb: True
  threatfox: False
  securitytrails: False  # DO NOT USE WITH FREE API KEY !!!
  virustotal: True
  shodan: False
  alienvault: False
  bgp_ranking: False
  urlhaus: False
arguments:
  quiet: False
  name: "analysis name"
sniffing:
 interface: eth0
 filter:  # BPF filtering
 timeout: 15  # seconds
 filename: test.pcap # output file 
thresholds:
  MAX_FREQUENCY: 10 # percentage
  MAX_DURATION: 14000 # seconds
  MAX_HTTP_SIZE: 50000 # bytes
  MAX_SUBDOMAIN_LENGTH: 30 # chars
plugins: