name:
  "analysis name"

api_keys:
  abuseipdb: "11111"
  virustotal: "22222"
  shodan: "33333"

api_urls:
  abuseipdb: "https://api.abuseipdb.com/api/v2/check"
  threatfox: "https://threatfox-api.abuse.ch/api/v1/"
  virustotal: "https://www.virustotal.com/vtapi/v2/"
  shodan: "https://api.shodan.io/"
  alienvault: "https://otx.alienvault.com/api/v1/indicators/"
  urlhaus: "https://urlhaus-api.abuse.ch/v1/"

settings:
  statistics_top_count: 5 # number of displayed values
  chunk_size: 1000 # number of values in one database query 

feeds:
  tor_node_list: "https://www.dan.me.uk/torlist/"
  tor_exit_node_list: "https://www.dan.me.uk/torlist/?exit"
  crypto_domains: "https://blocklistproject.github.io/Lists/alt-version/crypto-nl.txt"
  ja3_rules: "https://rules.emergingthreats.net/open/suricata-5.0/rules/emerging-ja3.rules"

file_paths:
  tor_node_list_path: "iocs/tor/tor_nodes.json"
  crypto_domain_list_path: "iocs/crypto_domains/crypto_domains.json"
  ja3_rules_path: "iocs/ja3/ja3_rules.json"
  domain_whitelist_path: "config/domain_whitelist.txt"
  c2_tls_certificate_values_path: "config/c2_tls_certificate_values.json"
  report_template_path : "templates/report_template.html"

enrichment_services:
  abuseipdb: False
  threatfox: False
  virustotal: False
  shodan: False
  alienvault: False
  urlhaus: False

sniffing:
 interface: eth0
 filter:  # BPF filtering
 timeout: 15  # seconds
 filename: test.pcap # output file 

thresholds:
  MAX_FREQUENCY: 10 # percentage
  MAX_DURATION: 14000 # seconds
  MAX_HTTP_SIZE: 50000 # bytes
  MAX_SUBDOMAIN_LENGTH: 30 # chars
  
plugins:  # optional
 C2Hunter: "/example/path/to/C2Hunter/db/c2_servers.db"
